# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.srcs/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/blockdesign_system_ila_0_2.xci
# IP: The module: 'blockdesign_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/bd_57cb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_57cb || ORIG_REF_NAME==bd_57cb} -quiet] -quiet

# IP: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/bd_57cb_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_57cb_ila_lib_0 || ORIG_REF_NAME==bd_57cb_ila_lib_0} -quiet] -quiet

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_57cb_ila_lib_0 || ORIG_REF_NAME==bd_57cb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_57cb_ila_lib_0 || ORIG_REF_NAME==bd_57cb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/bd_57cb_ila_lib_0_ooc.xdc

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/bd_57cb_ooc.xdc

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/blockdesign_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.srcs/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/blockdesign_system_ila_0_2.xci
# IP: The module: 'blockdesign_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/bd_57cb.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_57cb || ORIG_REF_NAME==bd_57cb} -quiet] -quiet

# IP: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/bd_57cb_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_57cb_ila_lib_0 || ORIG_REF_NAME==bd_57cb_ila_lib_0} -quiet] -quiet

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_57cb_ila_lib_0 || ORIG_REF_NAME==bd_57cb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_57cb_ila_lib_0 || ORIG_REF_NAME==bd_57cb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/ip/ip_0/bd_57cb_ila_lib_0_ooc.xdc

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/bd_0/bd_57cb_ooc.xdc

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/ip/blockdesign_system_ila_0_2/blockdesign_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
