set_property IOSTANDARD LVCMOS33 [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_txd]
set_property PACKAGE_PIN P18 [get_ports UART_rxd]
set_property PACKAGE_PIN N17 [get_ports UART_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {status_led_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status_led_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status_led_tri_o[0]}]
set_property PACKAGE_PIN M15 [get_ports {status_led_tri_o[0]}]
set_property PACKAGE_PIN L14 [get_ports {status_led_tri_o[1]}]
set_property PACKAGE_PIN G14 [get_ports {status_led_tri_o[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports Col_0_0]
set_property IOSTANDARD LVCMOS33 [get_ports Col_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports Col_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports Col_3_0]
set_property IOSTANDARD LVCMOS33 [get_ports Row_0_0]
set_property IOSTANDARD LVCMOS33 [get_ports Row_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports Row_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports {Data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Data_0[0]}]
set_property PACKAGE_PIN R14 [get_ports {Data_0[0]}]
set_property PACKAGE_PIN P14 [get_ports {Data_0[1]}]
set_property PACKAGE_PIN N16 [get_ports {Data_0[2]}]
set_property PACKAGE_PIN M14 [get_ports {Data_0[3]}]

set_property PACKAGE_PIN V13 [get_ports Col_3_0]

set_property PULLUP true [get_ports Col_3_0]


set_property IOSTANDARD LVCMOS33 [get_ports Row_3_0]
set_property PACKAGE_PIN V15 [get_ports Col_0_0]
set_property PACKAGE_PIN R16 [get_ports Col_1_0]
set_property PACKAGE_PIN U13 [get_ports Col_2_0]
set_property PACKAGE_PIN T15 [get_ports Row_0_0]
set_property PACKAGE_PIN T14 [get_ports Row_1_0]
set_property PACKAGE_PIN U12 [get_ports Row_2_0]
set_property PACKAGE_PIN V13 [get_ports Row_3_0]
set_property DRIVE 12 [get_ports Col_2_0]
set_property PULLUP true [get_ports Row_0_0]
set_property PULLUP true [get_ports Row_1_0]
set_property PULLUP true [get_ports Row_2_0]
set_property PULLUP true [get_ports Row_3_0]
set_property PACKAGE_PIN R14 [get_ports {data_out_0[0]}]
set_property PACKAGE_PIN P14 [get_ports {data_out_0[1]}]
set_property PACKAGE_PIN N16 [get_ports {data_out_0[2]}]
set_property PACKAGE_PIN M14 [get_ports {data_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out_0[1]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
