set_property IOSTANDARD LVCMOS33 [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_txd]
set_property PACKAGE_PIN P18 [get_ports UART_rxd]
set_property PACKAGE_PIN N17 [get_ports UART_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {status_led_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status_led_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status_led_tri_o[0]}]
set_property PACKAGE_PIN M15 [get_ports {status_led_tri_o[0]}]
set_property PACKAGE_PIN L14 [get_ports {status_led_tri_o[1]}]
set_property PACKAGE_PIN G14 [get_ports {status_led_tri_o[2]}]
