# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/blockdesign/blockdesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign || ORIG_REF_NAME==blockdesign} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_axi_gpio_0_0/blockdesign_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_axi_gpio_0_0 || ORIG_REF_NAME==blockdesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_processing_system7_0_0/blockdesign_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_processing_system7_0_0 || ORIG_REF_NAME==blockdesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_xlconcat_0_0/blockdesign_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_xlconcat_0_0 || ORIG_REF_NAME==blockdesign_xlconcat_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_axi_gpio_1_0/blockdesign_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_axi_gpio_1_0 || ORIG_REF_NAME==blockdesign_axi_gpio_1_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_axi_gpio_2_0/blockdesign_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_axi_gpio_2_0 || ORIG_REF_NAME==blockdesign_axi_gpio_2_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_proc_sys_reset_0_0/blockdesign_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_proc_sys_reset_0_0 || ORIG_REF_NAME==blockdesign_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_axi_gpio_3_0/blockdesign_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_axi_gpio_3_0 || ORIG_REF_NAME==blockdesign_axi_gpio_3_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_xbar_0/blockdesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_xbar_0 || ORIG_REF_NAME==blockdesign_xbar_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_ps7_0_axi_periph_1/blockdesign_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_ps7_0_axi_periph_1 || ORIG_REF_NAME==blockdesign_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_keypad_0_0/blockdesign_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_keypad_0_0 || ORIG_REF_NAME==blockdesign_keypad_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_fifo_generator_0_0/blockdesign_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_fifo_generator_0_0 || ORIG_REF_NAME==blockdesign_fifo_generator_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_comunication_protocol_0_0/blockdesign_comunication_protocol_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_comunication_protocol_0_0 || ORIG_REF_NAME==blockdesign_comunication_protocol_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_util_vector_logic_0_0/blockdesign_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_util_vector_logic_0_0 || ORIG_REF_NAME==blockdesign_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_xlconstant_0_0/blockdesign_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_xlconstant_0_0 || ORIG_REF_NAME==blockdesign_xlconstant_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_util_reduced_logic_0_0/blockdesign_util_reduced_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_util_reduced_logic_0_0 || ORIG_REF_NAME==blockdesign_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_clk_divider_0_0/blockdesign_clk_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_clk_divider_0_0 || ORIG_REF_NAME==blockdesign_clk_divider_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_hold_detector_0_0/blockdesign_hold_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_hold_detector_0_0 || ORIG_REF_NAME==blockdesign_hold_detector_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_DeBounce_0_0/blockdesign_DeBounce_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_DeBounce_0_0 || ORIG_REF_NAME==blockdesign_DeBounce_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_auto_pc_0/blockdesign_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_auto_pc_0 || ORIG_REF_NAME==blockdesign_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Jochem/GitHub/Fontys/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/blockdesign_ooc.xdc
