# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/blockdesign/blockdesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign || ORIG_REF_NAME==blockdesign} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_clk_wiz_0_0/blockdesign_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_clk_wiz_0_0 || ORIG_REF_NAME==blockdesign_clk_wiz_0_0} -quiet] -quiet

# IP: bd/blockdesign/ip/blockdesign_keypad_0_0/blockdesign_keypad_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blockdesign_keypad_0_0 || ORIG_REF_NAME==blockdesign_keypad_0_0} -quiet] -quiet

# XDC: c:/_code/Git/MO8/mo8-digitaal-zender/mo8-digitaal-zender/mo8-digitaal-zender.gen/sources_1/bd/blockdesign/blockdesign_ooc.xdc
